apiVersion: v2
name: mongo-demo
description: A Helm chart for MongoDB and Mongo Express on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - mongodb
  - mongo-express
  - database
maintainers:
  - name: Saif Eddine
    email: haddedseif746@gmail.com