apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo-demo
type: Opaque
data:
  # username: admin (base64)
  mongo-root-username: YWRtaW4=
  # password: password123 (base64)
  mongo-root-password: cGFzc3dvcmQxMjM=