apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.credentials.username | b64enc }}
  mongo-root-password: {{ .Values.mongodb.credentials.password | b64enc }}