apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.mongoExpress.service.type }}
  selector:
    app: mongo-express
  ports:
  - protocol: TCP
    port: {{ .Values.mongoExpress.service.port }}
    targetPort: 8081
    {{- if eq .Values.mongoExpress.service.type "NodePort" }}
    nodePort: {{ .Values.mongoExpress.service.nodePort }}
    {{- end }}