apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-role-binding
  namespace: mongo-demo
subjects:
- kind: ServiceAccount
  name: mongo-sa
  namespace: mongo-demo
roleRef:
  kind: Role
  name: mongo-role
  apiGroup: rbac.authorization.k8s.io